substitutions:
  board: ESP32
  board_name: e3-2e_04
  comment: e3-2e 5m\3r\5io

  
esphome:
  name: $board_name
  platform: ESP32
  board: esp-wrover-kit
  comment: $comment

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

  
# Enable logging
logger:


# Enable Home Assistant API
api:
  reboot_timeout: 0s
ota:

web_server:
  port: 80

switch:
  - platform: restart
    name: "${board_name}_restart"
#########################Shield 3 Relay####################    
  - platform: gpio
    name: "${board_name}_relay_0_5"
    pin:
      pcf8574: pcf8574_3r_5io
      number: 5
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: False   
  - platform: gpio
    name: "${board_name}_relay_0_6"
    pin:
      pcf8574: pcf8574_3r_5io
      number: 6
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: False
  - platform: gpio
    name: "${board_name}__relay_0_4"
    pin:
      pcf8574: pcf8574_3r_5io
      number: 4
      # One of INPUT or OUTPUT
      mode: OUTPUT
      inverted: False
            
binary_sensor:
  - platform: status
    name: "${board_name}_status"
  - platform: gpio
    pin: 39
    name: "${board_name}_pin_39" #Пин можно использовать только на вход
    device_class: sound     
  - platform: gpio
    pin: 36
    name: "${board_name}_pin_36" #Пин можно использовать только на вход
    device_class: vibration     
  - platform: gpio
    pin: 35
    name: "${board_name}_pin_35" #Пин можно использовать только на вход
    device_class: motion
  - platform: gpio
    pin: 5
    name: "${board_name}_pin_5"  
  - platform: gpio
    pin: 17
    name: "${board_name}_pin_17" 
#########################Shield 5 IO####################
  - platform: gpio
    name: "${board_name}_pin_0_7"
    pin:
      pcf8574: pcf8574_3r_5io
      number: 7
      # One of INPUT or OUTPUT
      mode: input
      inverted: true
  - platform: gpio
    name: "${board_name}_pin_0_3"
    pin:
      pcf8574: pcf8574_3r_5io
      number: 3
      # One of INPUT or OUTPUT
      mode: input
      inverted: true
  - platform: gpio
    pin: 
      pcf8574: pcf8574_3r_5io
      number: 0
      # One of INPUT or OUTPUT
      mode: input
      inverted: false   
    name: "${board_name}_pin_0_0"
    device_class: motion
  - platform: gpio
    name: "${board_name}_pin_0_1"
    pin:
      pcf8574: pcf8574_3r_5io
      number: 1
      # One of INPUT or OUTPUT
      mode: input
      inverted: false
  - platform: gpio
    name: "${board_name}_pin_0_2"
    pin:
      pcf8574: pcf8574_3r_5io
      number: 2
      # One of INPUT or OUTPUT
      mode: input
      inverted: true

i2c:
  sda: 33
  scl: 32
  scan: True
  id: i2c_bus    
    
pcf8574:
  - id: 'pcf8574_3r_5io'
    address: 0x20
    pcf8575: False      
    
text_sensor:
  - platform: version
    name: "${board_name}_firmware"
  - platform: template
    name: "${board_name}_uptime_min"
    lambda: |-
      uint32_t uptime = (id(id_uptime).state);
      int minutes = (uptime % 3600) / 60;
      int hours = (uptime % 86400) / 3600;
      int days = uptime / 86400;
      if (days > 0) {
        return { (String(days) + " д." + String(hours) + " ч." + String(minutes) + " мин.").c_str() };
      }
      if (hours > 0) {
        return { (String(hours) + " ч. " + String(minutes) + " мин.").c_str() };
      } else {
        return { (String(minutes) + " мин.").c_str() };
      }
    update_interval: 60s
    icon: mdi:clock-start     
    
sensor: 
  - platform: uptime
    id: id_uptime
    internal: true
    name: "${board_name}_uptime"   

     
     
output:
#####RGBW STRIP#####
  - platform: ledc
    pin: 15
    id: out_red
  - platform: ledc
    pin: 4
    id: out_green 
  - platform: ledc
    pin: 12
    id: out_blue
  - platform: ledc
    pin: 14
    id: out_white 
#####White strip######
  - platform: ledc
    pin: 2
    id: out_white2  
    
light:
######RGBW STRIP###### 
  - platform: rgbw
    name: "${board_name}_led RGBW"
    red: out_red
    green: out_green
    blue: out_blue
    white: out_white
    effects:
      - strobe:
          name: Strobe Effect
          colors:
            - state: true
              brightness: 100%
              duration: 600ms
            - state: true
              duration: 600ms
              brightness: 0%
      - flicker:
          name: Flicker Effect With Custom Values
          alpha: 95%
          intensity: 1.5%
      - strobe:
          name: Strobe Effect With Custom Values
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 90%
              blue: 0%
              duration: 500ms
            - state: False
              duration: 250ms
            - state: True
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms    
####### White Strip#######
  - platform: monochromatic
    id: led_top_illumination
    output: out_white2
    name: ${board_name}_led_white
    default_transition_length: 1s
###### Adressable Led Strip#####
  - platform: fastled_clockless
    id: ws_led
    chipset: WS2812B
    pin: 0
    num_leds: 240
    rgb_order: BRG
    internal: false
    name: "${board_name}_WS2812_Light"
    effects:
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50
      - addressable_color_wipe:
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: False
      - addressable_scan:
      - addressable_scan:
          name: Scan Effect With Custom Values
          move_interval: 100ms
          scan_width: 1
      - addressable_twinkle:
      - addressable_twinkle:
          name: Twinkle Effect With Custom Values
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_random_twinkle:
      - addressable_random_twinkle:
          name: Random Twinkle Effect With Custom Values
          twinkle_probability: 5%
          progress_interval: 32ms
      - addressable_fireworks:
      - addressable_fireworks:
          name: Fireworks Effect With Custom Values
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: false
          fade_out_rate: 120
      - addressable_flicker:
      - addressable_flicker:
          name: Flicker Effect With Custom Values
          update_interval: 16ms
          intensity: 5%            

    
